name: flutter_template_app
description: Flutter Project Template

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate_annotations: ^2.0.0

  provider: ^5.0.0
  sembast: ^3.1.0+2
  in_app_purchase: ^1.0.5
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  flutter_translate: ^3.0.1
  package_info: ^2.0.2
  intl: ^0.17.0
  http: ^0.13.3
  get_it: ^7.1.3
  flutter_secure_storage: ^4.2.0
  cupertino_icons: ^1.0.3
  collection: ^1.15.0
  fluttertoast: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_translate_gen: ^2.0.0
  build_runner: ^2.0.4
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/

  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Ultralight.ttf
          weight: 100
        - asset: assets/fonts/SFUIDisplay-Thin.ttf
          weight: 200
        - asset: assets/fonts/SFUIDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFUIDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFUIDisplay-Black.ttf
          weight: 900